version: '3.8'
services:
  mqtt-server:
    image: ghcr.io/everest/everest-demo/mqtt-server:0.0.16
    platform: linux/amd64
    networks:
      - everest-net
    logging:
      driver: none
  manager:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - 8888:8888
    networks:
      - everest-net
    depends_on:
      - mqtt-server
    environment:
      - MQTT_SERVER_ADDRESS=mqtt-server
      - EVEREST_TARGET_URL=ws://host.docker.internal:8081/cp001
      - EVEREST_IMAGE_TAG=0.0.16
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  nodered:
    image: ghcr.io/everest/everest-demo/nodered:0.0.16
    platform: linux/amd64
    networks:
      - everest-net
    depends_on:
      - mqtt-server
    ports:
      - 1881:1880  # Change to a different host port
    environment:
      - MQTT_SERVER_ADDRESS=mqtt-server
      - FLOWS=/config/config-sil-two-evse-flow.json
networks:
  everest-net:
    driver: bridge
